repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks: # general hooks
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: trailing-whitespace

-   repo: local
    hooks: # code formatter
      - id: black
        name: black
        entry: black --config ./pyproject.toml .
        language: python
        pass_filenames: false

-   repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 --config .flake8 .
        language: python
        pass_filenames: false
