name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set environment variables
      run: |
        echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' >> $GITHUB_ENV
        echo 'ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}' >> $GITHUB_ENV
        echo 'DB_HOST=${{ secrets.DB_HOST }}' >> $GITHUB_ENV
        echo 'DB_NAME=${{ secrets.DB_NAME }}' >> $GITHUB_ENV
        echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> $GITHUB_ENV
        echo 'DB_PORT=${{ secrets.DB_PORT }}' >> $GITHUB_ENV
        echo 'DB_USER=${{ secrets.DB_USER }}' >> $GITHUB_ENV
        echo 'DEBUG=${{ secrets.DEBUG }}' >> $GITHUB_ENV
        echo 'MYSQL=${{ secrets.MYSQL }}' >> $GITHUB_ENV

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" --silent; do
          sleep 1
        done

    - name: Run Migrations
      env:
        DATABASE_URL: mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@127.0.0.1:3306/${{ secrets.DB_NAME }}
      run: |
        python manage.py migrate

    - name: Run Tests
      env:
        DATABASE_URL: mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@127.0.0.1:3306/${{ secrets.DB_NAME }}
      run: |
        python manage.py test
